guides/testing の翻訳
crystal-jp/ja.crystal-lang.org pull request #102
Opened 2020-05-22 00:14 UTC by arcage

一通り日本語にしてみました。

現時点で、

・spec(s) は英語のまま spec としています。
・Expectation(s)をうまいこと日本語にできず、今のところ英語のままになっています。
・Example(s)の訳が「実行例」で良いのか微妙に悩んでいます。

2020-05-22 01:27 UTC, makenowjust requested changes
ちょっと気になった部分をコメントしました

2020-05-22 01:27 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/testing.md
> +基本的な spec はこのうようになります。
「このうよう」→「このよう」

2020-05-22 01:27 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/testing.md
> +### コマンド例
これって例外訳文で登録していますか？　ただ、例外訳文もファイル名の変更に追従できなくて面倒なのと、単に「例」だけでも意味は通じるので、それでもいい気がします。

2020-05-22 01:32 UTC, MakeNowJust commented
@arcage 「Expectation」は「期待する結果」とかでいい気がしますけど

2020-05-22 01:34 UTC, makenowjust requested changes

2020-05-22 01:34 UTC, MakeNowJust commented on i18n/omegat/project_save.tmx
> +        <seg>基本的な spec はこのうようになります。</seg>
```suggestion
        <seg>基本的な spec はこのようになります。</seg>
```

2020-05-22 01:34 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/testing.md
> +基本的な spec はこのうようになります。
```suggestion
基本的な spec はこのようになります。
```

2020-05-22 01:35 UTC, MakeNowJust commented
いや、でもExpectationsのままでいいかもしれません。

(Javaの文化だと「Expectations (期待値)」と訳すらしい)

2020-05-22 04:11 UTC, MakeNowJust commented
@arcage リンクのURLも翻訳対象に含めるためOmegaTのフィルタ設定が必要になったので、それもお願いします。

https://github.com/crystal-jp/ja.crystal-lang.org/blob/master/CONTRIBUTING.md#フィルタの設定

2020-05-24 06:15 UTC, arcage commented
少し面倒なことになっちゃったようなのでいったん閉じます。

2020-05-24 06:15 UTC, closed without merging