feat: guide/concurrency 1st translation
crystal-jp/ja.crystal-lang.org pull request #89
Opened 2020-04-29 15:21 UTC by arcage

過去の下書きを引っ張り出してきて一部手を入れています。

日本語として通りを良くするために意訳っぽくなっている部分もあると思いますので、問題があれば指摘お願いします。

2020-04-29 15:23 UTC, arcage commented
locale/ja/crystal-book/book.json が消えちゃってますが、何か手順間違えたでしょうか？

2020-04-29 15:32 UTC, MakeNowJust commented
@arcage どうして `book.json` が消えてるんだろう？ `jq` が入ってなくて生成に失敗してるとかかな‥‥。

とりあえず消えるのは困るのでそこは直してもらえるとありがたいです。

2020-04-29 15:33 UTC, arcage commented
了解です。
もう少し色々試してみます。

2020-04-30 00:21 UTC, arcage commented
ご指摘の通り、手元のMacにjqが入っていませんでした。

インストール後、ja 側 book.json のタイムスタンプを弄って `make locale/ja` を改めて実行してみました。

book.jsonの内容から、pluginsConfig.gaの内容が落ちていますが、Makefileを見ると想定通りの動きに思います。

2020-05-04 09:54 UTC, MakeNowJust commented
@arcage レビューして大丈夫そうならマージしようかと思っているのですが大丈夫でしょうか？

2020-05-04 09:57 UTC, arcage commented
お願いします。
とりあえず、今日一度確認して、細かい修正はしました。

2020-05-04 10:21 UTC, makenowjust requested changes
いくつかタイポなどを指摘しました。修正お願いします

2020-05-04 10:21 UTC, makenowjust commented on locale/ja/crystal-book/guides/concurrency.md
> +I/Oに関係するものであればなんでも、イベントループのお世話になっています。おかげで、たとえ時間のかかる処理がIOに対して行われていてイベントループがその終了を待っている状態でも、プログラムは別のファイバを実行することができます。ソケット経由でのデータの受信操作などは、こうした時間がかかる処理の一例です。
最初の一文が「I/O」で、次の文では「IO」になっているのが気になります。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +### チャンネル（Channel）
根本的な修正で申し訳ないのですが、並列システムの文脈では"channel"は「チャネル」と訳される傾向があるので、そちらの方が良いのではないかと思います。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +* "もう使用されない" メモリを掃除する「ガーベージコレクタ」
他の翻訳との一貫性を考えると、「ガーベージコレクタ」ではなく「ガベージコレクタ」が良いと思います。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +ファイバはスレッドと違って協調的に動作します。スレッドはプリエンプティブ（非同期マルチタスク）なので，OSはいつでもスレッドに割り込んで別のスレッドを実行することができます。ファイバはラインタイムスケジューラに対して、明示的に「他のファイバへ処理を切り替えて良い」と伝える必要があります。例えばI/O による待ちが発生していた場合、ファイバはランタイムスケジューラに対して「おーい，自分はIOが使え
ここも「I/O」と「IO」が混在しています。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +現時点ではシングルスレッドでしかコードを実行できなため、複数のファイバから同じクラス変数を参照や変更しても問題なく動作します。しかし、一旦マルチスレーッド（並列処理）が言語に導入されると、そういう訳にもいかなくなります。このことが、データのやりとりにチャンネルを使い、メッセージをチャンネル経由で送受信することが推奨される理由です。チャンネルは内部的にデータ競合を避けるためのロック機構を実装してい
「**スレーッド**」？

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +64ビットマシンでは数百万ものファイバを生成することができます32ビットマシンの場合はそれほど多くはなく、生成できるファイバは512本だけです。しかし，32ビットマシンはもはや使用されなくなりつつありますので、我々は将来を見据えて64ビットマシンにより注力しています。
「できます」と「32ビットマシン」の間に句点が必要です。

それとファイバの数え方は「○本」ではなく「○個」もしくは「○つ」でいい気がします。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +64ビットマシンでは数百万ものファイバを生成することができます32ビットマシンの場合はそれほど多くはなく、生成できるファイバは512本だけです。しかし，32ビットマシンはもはや使用されなくなりつつありますので、我々は将来を見据えて64ビットマシンにより注力しています。
あとここの「しかし」のあとの読点がコンマになってます。

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +今度は正しく動作しました。ばぜかと言うと、[Proc](http://crystal-lang.org/api/Proc.html)を生成してそれに`i`を渡しているからです。こうすることで、`i`の値がコピーされ、生成されたファイバが使用するのはそのコピーになります。
「ばぜかというと」→「なぜかというと」

2020-05-04 10:21 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +プログラムがいつ`receive`を実行したか、つまりファイバをブロックして他のファイバに実行が切り替わったおかに注目してください。`send` が実行されると、そのチャンネルを待ち受けていたファイバの実行が再開されます。
「切り替わったおかに」→「切り替わったかに」

2020-05-04 11:29 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +コンカレント・マーク＆スイープ方式で実装されたガーベジコレクタ（GC）（現時点では[Boehm GC](http://www.hboehm.info/gc/)）を除いて、Crystalのプログラムは単一のOSスレッド上で実行されます。
「ガーベジ」ではなく「ガベージ」です

2020-05-04 11:30 UTC, arcage commented
ありがとうございます。

指摘いただいた部分を修正してコミットしました。
よろしくお願いします。

なお、IOはI/Oに統一しました。
PerformanceのページでもI/Oまわりは良く言及されるので、型名の「IO」でない場合はそちらにも反映させようと思います。

2020-05-04 11:30 UTC, MakeNowJust commented on locale/ja/crystal-book/guides/concurrency.md
> +コンカレント・マーク＆スイープ方式で実装されたガーベジコレクタ（GC）（現時点では[Boehm GC](http://www.hboehm.info/gc/)）を除いて、Crystalのプログラムは単一のOSスレッド上で実行されます。
@arcage これだけ目についてしまったので対応おねがいします。そうしたらマージしたいと思います。

2020-05-04 11:34 UTC, makenowjust approved these changes

2020-05-04 11:35 UTC, merged

2020-05-04 11:35 UTC, arcage commented on locale/ja/crystal-book/guides/concurrency.md
> +コンカレント・マーク＆スイープ方式で実装されたガーベジコレクタ（GC）（現時点では[Boehm GC](http://www.hboehm.info/gc/)）を除いて、Crystalのプログラムは単一のOSスレッド上で実行されます。
すいませんでした。
修正してコミットしました。

2020-05-04 11:35 UTC, MakeNowJust commented
@arcage こちらこそありがとうございました。Performanceの方もよろしくお願いします。

2020-05-04 11:35 UTC, arcage commented on locale/ja/crystal-book/guides/concurrency.md
> +コンカレント・マーク＆スイープ方式で実装されたガーベジコレクタ（GC）（現時点では[Boehm GC](http://www.hboehm.info/gc/)）を除いて、Crystalのプログラムは単一のOSスレッド上で実行されます。
Performance 側もこの辺り反映させます。